"use client";
import { useEffect, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { ChartLineUpIcon, UsersIcon, GlobeHemisphereWestIcon, ClipboardTextIcon, DatabaseIcon, ArrowUpRightIcon, ArrowsClockwiseIcon, MagnifyingGlassIcon, CaretDownIcon, CaretLeftIcon, CaretRightIcon, SignOutIcon, ShieldCheckIcon, XIcon, ListIcon, DownloadSimpleIcon, EnvelopeSimpleIcon, ClockIcon, FunnelSimpleIcon, MonitorIcon, CheckIcon, WarningCircleIcon } from "@phosphor-icons/react";
import { logout } from "@/app/login/actions";
import type { Analytics, Signup } from "@/lib/analytics";
import type { Filters } from "@/lib/filters";
import { SignupChart, Segments } from "./charts";

const number = (n: number) => n.toLocaleString("en-US");
function date(value: string | null, time = false) { return value ? new Date(value).toLocaleString("en-US", { timeZone: "Asia/Jakarta", day: "numeric", month: "short", year: "numeric", ...(time ? { hour: "2-digit", minute: "2-digit" } : {}) }) : "—"; }
const navigation = [{ id: "overview", label: "Overview", icon: ChartLineUpIcon }, { id: "waitlist", label: "Waitlist", icon: UsersIcon }, { id: "audience", label: "Audience", icon: GlobeHemisphereWestIcon }, { id: "forms", label: "Forms", icon: ClipboardTextIcon }];
const titles: Record<string, { title: string; subtitle: string }> = {
  overview: { title: "Overview", subtitle: "Monitor waitlist growth and audience activity." },
  waitlist: { title: "Waitlist", subtitle: "Search registrations, review details, and export records." },
  audience: { title: "Audience", subtitle: "Explore audience segments using registration data." },
  forms: { title: "Forms", subtitle: "Review landing page forms and response counts." },
  sources: { title: "Data sources", subtitle: "Review connection status, metric coverage, and workspace access." }
};
export function Dashboard({ data, filters, view }: { data: Analytics | null; filters: Filters; view: string }) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [pending, startTransition] = useTransition();
  const [menuOpen, setMenuOpen] = useState(false);
  const [selected, setSelected] = useState<Signup | null>(null);
  const [search, setSearch] = useState(filters.search);
  const [exporting, setExporting] = useState(false);
  const [exportError, setExportError] = useState("");
  const dialogRef = useRef<HTMLDialogElement>(null);
  useEffect(() => setSearch(filters.search), [filters.search]);
  useEffect(() => { if (selected) dialogRef.current?.showModal(); else dialogRef.current?.close(); }, [selected]);
  function update(key: string, value: string) {
    const params = new URLSearchParams(searchParams.toString());
    if (value) params.set(key, value); else params.delete(key);
    if (key !== "page") params.delete("page");
    startTransition(() => router.push("/?" + params.toString(), { scroll: false }));
  }
  const viewHref = (id: string) => { const p = new URLSearchParams(searchParams.toString()); p.set("view", id); p.delete("page"); p.delete("search"); return "/?" + p.toString(); };
  async function exportCsv() {
    setExporting(true); setExportError("");
    try {
      const response = await fetch("/api/export?" + searchParams.toString());
      if (response.status === 401) { router.push("/login"); return; }
      if (!response.ok) { const body = await response.json(); throw new Error(body.error); }
      const blob = await response.blob(); const url = URL.createObjectURL(blob);
      const a = document.createElement("a"); a.href = url; a.download = "enemites-waitlist.csv"; a.click(); URL.revokeObjectURL(url);
    } catch (error) { setExportError(error instanceof Error ? error.message : "Export failed."); }
    finally { setExporting(false); }
  }
  const activeFilters = Boolean(filters.device || filters.age || filters.updates);
  return <div className="workspace"><a className="skip-link" href="#main">Skip to main content</a>
    {menuOpen && <button className="mobile-scrim" aria-label="Close navigation" onClick={() => setMenuOpen(false)}/>}
    <aside className={`sidebar ${menuOpen ? "open" : ""}`}><Link href="/" className="brand"><span className="brand-mark">e</span><span>enemites<small>ANALYTICS</small></span></Link>
      <div className="workspace-switch"><span className="workspace-avatar">E</span><span>Enemites workspace<small>Landing page</small></span><CaretDownIcon size={13}/></div>
      <div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(item => <Link key={item.id} href={viewHref(item.id)} onClick={() => setMenuOpen(false)} className={`nav-link ${view === item.id ? "active" : ""}`} aria-current={view === item.id ? "page" : undefined}><item.icon size={19}/>{item.label}{item.id === "waitlist" && data && <span className="nav-count">{data.all.total}</span>}</Link>)}</nav>
      <div className="nav-label system-label">SYSTEM</div><Link className={`nav-link ${view === "sources" ? "active" : ""}`} href={viewHref("sources")} onClick={() => setMenuOpen(false)}><DatabaseIcon size={19}/>Data sources</Link>
      <div className="sidebar-bottom"><div className="connection"><span className={`status-dot ${data ? "" : "offline"}`}/><span>{data ? "Database connected" : "Connection unavailable"}<small>Neon · Production</small></span></div><div className="team-account"><div className="team-avatar">EN</div><span>Enemites team<small>Internal access</small></span><form action={logout}><button aria-label="Sign out" title="Sign out"><SignOutIcon size={19}/></button></form></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><button className="menu-toggle" aria-label="Open navigation" onClick={() => setMenuOpen(true)}><ListIcon size={22}/></button><div className="breadcrumb">Workspace<span>/</span><b>{view === "sources" ? "Data sources" : navigation.find(x => x.id === view)?.label}</b></div><div className="topbar-right"><span className="internal-badge"><ShieldCheckIcon size={14}/>Internal only</span><a href="https://enemites.com" target="_blank" rel="noreferrer">Landing page<ArrowUpRightIcon size={15}/></a></div></header>
      <main id="main" className={`main-content ${pending ? "is-pending" : ""}`} aria-busy={pending}>
        <div className="page-heading"><div><div className="eyebrow">LANDING PAGE ANALYTICS</div><h1>{titles[view].title}</h1><p>{titles[view].subtitle}</p></div><div className="heading-controls"><button className={`icon-button ${pending ? "spin" : ""}`} aria-label="Refresh data" title="Refresh data" onClick={() => startTransition(() => router.refresh())}><ArrowsClockwiseIcon size={18}/></button>{view !== "sources" && <label className="period-select"><ClockIcon size={16}/><select aria-label="Date range" value={filters.range} onChange={e => update("range", e.target.value)}><option value="all">All time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><CaretDownIcon size={12}/></label>}</div></div>
        {!data ? <section className="panel error-panel"><WarningCircleIcon size={30}/><h2>Unable to load data</h2><p>Check the Neon connection and dashboard_reader permissions. Data will appear when the connection is restored.</p><button className="button" onClick={() => startTransition(() => router.refresh())}>Try again</button></section> : <>
          <div className="data-line"><span><span className="status-dot"/>Live data from Neon</span><span>Updated {new Date(data.updatedAt).toLocaleTimeString("en-US", { timeZone: "Asia/Jakarta", hour: "2-digit", minute: "2-digit" })} UTC+7</span><span className="data-line-last">Latest registration: {date(data.all.last)}</span></div>
          {view !== "forms" && view !== "sources" && <div className="filter-row"><FunnelSimpleIcon size={16}/><span>Audience filters</span><select aria-label="Device" value={filters.device} onChange={e => update("device", e.target.value)}><option value="">All devices</option><option>Desktop</option><option>Mobile</option><option>Tablet</option><option value="unknown">Unknown</option></select><select aria-label="Age group" value={filters.age} onChange={e => update("age", e.target.value)}><option value="">All ages</option>{["<10", "10-18", "18-20", "20+"].map(age => <option key={age}>{age}</option>)}<option value="unknown">Unknown</option></select><select aria-label="Update consent" value={filters.updates} onChange={e => update("updates", e.target.value)}><option value="">All preferences</option><option value="yes">Opted in to updates</option><option value="no">Not opted in</option></select>{activeFilters && <button className="reset-filter" onClick={() => { const p = new URLSearchParams(searchParams.toString()); ["device", "age", "updates", "page"].forEach(k => p.delete(k)); startTransition(() => router.push("/?" + p.toString(), { scroll: false })); }}>Reset<XIcon size={12}/></button>}</div>}
          {view === "overview" && <>
            <div className="stats-grid"><Metric label="Waitlist registrations" value={number(data.stats.total)} icon={<UsersIcon/>} note={filters.range === "all" ? "Across the selected period" : data.previous === 0 ? "Previous period: 0 registrations" : `${Math.round((data.stats.total - (data.previous ?? 0)) / (data.previous || 1) * 100)}% vs previous period`} accent/>
              <Metric label="Opted in to updates" value={number(data.stats.opted_in)} icon={<EnvelopeSimpleIcon/>} note={`${data.stats.total ? Math.round(data.stats.opted_in / data.stats.total * 100) : 0}% opted in`}/>
              <Metric label="Countries represented" value={number(data.stats.countries)} icon={<GlobeHemisphereWestIcon/>} note={`${data.stats.unknown_country} registrations with unknown location`}/>
              <Metric label="Landing page conversion" value="—" icon={<ChartLineUpIcon/>} note="Visitor data unavailable" muted/>
            </div><div className="overview-charts"><SignupChart points={data.chart} total={data.stats.total}/><Segments title="Audience devices" description="Device at registration" segments={data.groups.device_type} total={data.stats.total} donut/></div>
            <div className="insight-strip"><div className="insight-icon"><DatabaseIcon size={19}/></div><div><b>Registration data only</b><p>Metrics cover waitlist registrations. Traffic, acquisition sources, and conversion data are not yet recorded.</p></div><Link href={viewHref("sources")}>View sources<ArrowUpRightIcon size={15}/></Link></div>
          </>}
          {(view === "overview" || view === "waitlist") && <section className="panel table-panel"><div className="panel-head table-heading"><div><h2>{view === "overview" ? "Recent registrations" : "Waitlist records"}<span className="count-pill">{number(data.matches)}</span></h2><p>{filters.search ? `Search results for “${filters.search}”` : "Registrations matching the selected period and filters"}</p></div><div className="table-actions"><form className="search-field" onSubmit={e => { e.preventDefault(); update("search", search); }}><MagnifyingGlassIcon size={16}/><input aria-label="Search registrations" placeholder="Search name, email, phone…" value={search} onChange={e => setSearch(e.target.value)}/>{search && <button type="button" aria-label="Clear search" onClick={() => { setSearch(""); update("search", ""); }}><XIcon size={13}/></button>}</form><button className="button export-button" disabled={exporting || data.matches === 0} onClick={exportCsv}><DownloadSimpleIcon size={16}/>{exporting ? "Exporting…" : "Export CSV"}</button></div></div>
            {exportError && <p role="alert" className="export-error">{exportError}</p>}
            <div className="table-scroll"><table><thead><tr><th>Registrant</th><th>Country</th><th>Device</th><th>Age</th><th>Update</th><th>Registered</th><th><span className="sr-only">Detail</span></th></tr></thead><tbody>{data.signups.map(row => <tr key={row.id}><td><button className="person-cell" onClick={() => setSelected(row)}><span className="person-avatar">{row.name.trim().slice(0, 2).toUpperCase()}</span><span><b>{row.name}</b><small>{row.email}</small></span></button></td><td>{row.country?.startsWith("Local (") ? "Unknown" : row.country || "Unknown"}{row.city && <small className="cell-secondary">{row.city}</small>}</td><td><span className="device-cell"><MonitorIcon size={14}/>{row.device_type || "Unknown"}</span></td><td>{row.age_group || "—"}</td><td><span className={`consent ${row.receive_updates ? "yes" : ""}`}>{row.receive_updates === null ? "Unknown" : row.receive_updates ? <><CheckIcon size={12}/>Yes</> : "No"}</span></td><td className="date-cell">{date(row.created_at)}</td><td><button className="row-arrow" aria-label={`Detail ${row.name}`} onClick={() => setSelected(row)}><ArrowUpRightIcon size={17}/></button></td></tr>)}</tbody></table></div>
            {data.signups.length === 0 && <div className="empty-state"><UsersIcon size={30}/><h3>{filters.search ? "No matching registrations" : "No registrations yet"}</h3><p>{filters.search ? "Try a different name or email, or clear the search." : "New registrations will appear here. Select All time to view the full history."}</p></div>}
            <div className="table-footer"><span>{data.matches ? `${(data.page - 1) * 10 + 1}–${Math.min(data.page * 10, data.matches)} of ${number(data.matches)} registrations` : "0 registrations"}</span><div><button disabled={data.page <= 1 || pending} aria-label="Previous page" onClick={() => update("page", String(data.page - 1))}><CaretLeftIcon size={14}/></button><span>Page {data.page} of {data.pages}</span><button disabled={data.page >= data.pages || pending} aria-label="Next page" onClick={() => update("page", String(data.page + 1))}><CaretRightIcon size={14}/></button></div></div>
          </section>}
          {view === "audience" && <><div className="audience-intro"><span className="big-number">{number(data.stats.total)}</span><span>registrations in the selected segment<br/><small>Missing locations and timezone-based locations are grouped as unknown.</small></span></div><div className="audience-grid"><Segments title="Country" segments={data.groups.country} total={data.stats.total}/><Segments title="Age group" segments={data.groups.age_group} total={data.stats.total}/><Segments title="Device" segments={data.groups.device_type} total={data.stats.total} donut/><Segments title="Browser" segments={data.groups.browser} total={data.stats.total}/><Segments title="Operating system" segments={data.groups.operating_system} total={data.stats.total}/><Segments title="Update preferences" segments={[{ label: "Opted in to updates", count: data.stats.opted_in }, { label: "Not opted in", count: data.stats.total - data.stats.opted_in }]} total={data.stats.total} donut/></div></>}
          {view === "forms" && <><div className="stats-grid forms-stats"><Metric label="Total forms" value={String(data.forms.length)} icon={<ClipboardTextIcon/>} note="All forms in the database"/><Metric label="Active forms" value={String(data.forms.filter(f => f.is_active && (!f.expires_at || new Date(f.expires_at) > new Date(data.updatedAt))).length)} icon={<CheckIcon/>} note="Active and not expired"/><Metric label="Responses in period" value={String(data.forms.reduce((n, f) => n + f.count, 0))} icon={<EnvelopeSimpleIcon/>} note="Within the selected date range"/></div><section className="panel"><div className="panel-head"><div><h2>Landing page forms</h2><p>Form and response data from the shared database</p></div></div>{data.forms.length ? <div className="forms-list">{data.forms.map(f => <article key={f.id}><ClipboardTextIcon size={24}/><div><h3>{f.title}</h3><p>{f.slug}</p></div><span className="consent">{f.is_active && (!f.expires_at || new Date(f.expires_at) > new Date(data.updatedAt)) ? "Active" : "Inactive / expired"}</span><b>{f.count} responses in this period<small className="cell-secondary">{f.total_count} all time</small></b></article>)}</div> : <div className="empty-state forms-empty"><div className="empty-icon"><ClipboardTextIcon size={30}/></div><h3>No forms yet</h3><p>Forms created on the landing page will appear here with their response counts.</p><a className="button" href="https://enemites.com" target="_blank" rel="noreferrer">Open landing page<ArrowUpRightIcon size={15}/></a></div>}</section><p className="panel-note">Audience filters apply to the waitlist. Form responses follow the selected date range only.</p></>}
          {view === "sources" && <><section className="panel source-card"><div className="panel-head"><div><h2>Database connection</h2><p>Shared with the waitlist website</p></div><span className="connected-pill"><span className="status-dot"/>Connected</span></div><dl><div><dt>Provider</dt><dd>Neon Postgres</dd></div><div><dt>Project</dt><dd className="mono">floral-flower-85390584</dd></div><div><dt>Database / branch</dt><dd>neondb / production</dd></div><div><dt>Dashboard access</dt><dd>Read-only · dashboard_reader</dd></div><div><dt>Reporting timezone</dt><dd>Asia/Jakarta (UTC+7)</dd></div><div><dt>Latest registration</dt><dd>{date(data.all.last, true)}</dd></div><div><dt>Frontend</dt><dd>Next.js · Vercel / enemites-analytics</dd></div></dl></section><section className="panel source-card"><div className="panel-head"><div><h2>Analytics coverage</h2><p>Metrics available from the current data source</p></div></div><div className="coverage-list">{[["Waitlist and update consent", "Available", true], ["Age, country, device, browser", "Available when recorded", true], ["Forms and response counts", "Available", true], ["Visitors, pageviews, traffic sources", "Not recorded", false], ["Visitor-to-waitlist conversion rate", "Requires visitor data", false]].map(([label, status, yes]) => <div key={String(label)}><span>{label}</span><span className={yes ? "coverage-yes" : "coverage-no"}>{status}</span></div>)}</div><div className="source-footnote">The dashboard reads <code>waitlist</code>, <code>enemites_forms</code>, and <code>enemites_form_submissions</code>. All metrics use recorded data; no sample data or estimates.</div></section></>}
          <footer className="page-footer"><span>Enemites analytics<span className="footer-dot">·</span>Internal workspace</span><span><ShieldCheckIcon size={13}/>Read-only access<span className="footer-dot">·</span>UTC+7</span></footer>
        </>}
      </main>
    </div>
    <dialog ref={dialogRef} className="detail-dialog" onCancel={() => setSelected(null)} onClick={e => { if (e.target === e.currentTarget) setSelected(null); }}>{selected && <div className="detail-content"><div className="detail-head"><span className="eyebrow">REGISTRATION DETAILS</span><button className="icon-button" aria-label="Close details" onClick={() => setSelected(null)}><XIcon size={19}/></button></div><span className="detail-avatar">{selected.name.slice(0, 2).toUpperCase()}</span><h2>{selected.name}</h2><p>{selected.email}</p><dl>{[["Phone / WhatsApp", selected.phone_number], ["Age group", selected.age_group], ["Update consent", selected.receive_updates === null ? "Unknown" : selected.receive_updates ? "Yes" : "No"], ["Country", selected.country], ["City", selected.city], ["Device", selected.device_type], ["Browser", selected.browser], ["Operating system", selected.operating_system], ["Registered (UTC+7)", date(selected.created_at, true)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "Unknown"}</dd></div>)}</dl><p className="detail-note"><ShieldCheckIcon size={14}/>Internal data · Enemites team only</p></div>}</dialog>
  </div>;
}
function Metric({ label, value, note, icon, accent = false, muted = false }: { label: string; value: string; note: string; icon: React.ReactNode; accent?: boolean; muted?: boolean }) {
  return <section className={`metric ${accent ? "accent" : ""} ${muted ? "muted-metric" : ""}`}><div className="metric-label"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><div className="metric-note">{note}</div></section>;
}
