"use client";
import { useEffect, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { ChartLineUpIcon, UsersIcon, GlobeHemisphereWestIcon, ClipboardTextIcon, DatabaseIcon, ArrowUpRightIcon, ArrowsClockwiseIcon, MagnifyingGlassIcon, CaretDownIcon, CaretLeftIcon, CaretRightIcon, SignOutIcon, ShieldCheckIcon, XIcon, ListIcon, DownloadSimpleIcon, EnvelopeSimpleIcon, ClockIcon, FunnelSimpleIcon, MonitorIcon, CheckIcon, WarningCircleIcon } from "@phosphor-icons/react";
import { logout } from "@/app/login/actions";
import type { Analytics, Signup } from "@/lib/analytics";
import type { Filters } from "@/lib/filters";
import { SignupChart, Segments } from "./charts";

const number = (n: number) => n.toLocaleString("id-ID");
function date(value: string | null, time = false) { return value ? new Date(value).toLocaleString("id-ID", { timeZone: "Asia/Jakarta", day: "numeric", month: "short", year: "numeric", ...(time ? { hour: "2-digit", minute: "2-digit" } : {}) }) : "—"; }
const navigation = [{ id: "overview", label: "Ringkasan", icon: ChartLineUpIcon }, { id: "waitlist", label: "Waitlist", icon: UsersIcon }, { id: "audience", label: "Audiens", icon: GlobeHemisphereWestIcon }, { id: "forms", label: "Formulir", icon: ClipboardTextIcon }];
const titles: Record<string, { title: string; subtitle: string }> = {
  overview: { title: "Setiap pendaftar, sebuah awal.", subtitle: "Pantau pertumbuhan landing page dan kenali audiens Enemites." },
  waitlist: { title: "Orang-orang di balik angka.", subtitle: "Telusuri pendaftar, lihat detail, dan ekspor waitlist untuk tim." },
  audience: { title: "Kenali siapa yang bergabung.", subtitle: "Distribusi audiens berdasarkan data saat mereka mendaftar." },
  forms: { title: "Dengarkan audiens Anda.", subtitle: "Pantau formulir dan jumlah respons dari landing page." },
  sources: { title: "Data yang dapat ditelusuri.", subtitle: "Status koneksi, cakupan metrik, dan akses workspace ini." }
};
export function Dashboard({ data, filters, view }: { data: Analytics | null; filters: Filters; view: string }) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [pending, startTransition] = useTransition();
  const [menuOpen, setMenuOpen] = useState(false);
  const [selected, setSelected] = useState<Signup | null>(null);
  const [search, setSearch] = useState(filters.search);
  const [exporting, setExporting] = useState(false);
  const [exportError, setExportError] = useState("");
  const dialogRef = useRef<HTMLDialogElement>(null);
  useEffect(() => setSearch(filters.search), [filters.search]);
  useEffect(() => { if (selected) dialogRef.current?.showModal(); else dialogRef.current?.close(); }, [selected]);
  function update(key: string, value: string) {
    const params = new URLSearchParams(searchParams.toString());
    if (value) params.set(key, value); else params.delete(key);
    if (key !== "page") params.delete("page");
    startTransition(() => router.push("/?" + params.toString(), { scroll: false }));
  }
  const viewHref = (id: string) => { const p = new URLSearchParams(searchParams.toString()); p.set("view", id); p.delete("page"); p.delete("search"); return "/?" + p.toString(); };
  async function exportCsv() {
    setExporting(true); setExportError("");
    try {
      const response = await fetch("/api/export?" + searchParams.toString());
      if (response.status === 401) { router.push("/login"); return; }
      if (!response.ok) { const body = await response.json(); throw new Error(body.error); }
      const blob = await response.blob(); const url = URL.createObjectURL(blob);
      const a = document.createElement("a"); a.href = url; a.download = "enemites-waitlist.csv"; a.click(); URL.revokeObjectURL(url);
    } catch (error) { setExportError(error instanceof Error ? error.message : "Ekspor gagal."); }
    finally { setExporting(false); }
  }
  const activeFilters = Boolean(filters.device || filters.age || filters.updates);
  return <div className="workspace"><a className="skip-link" href="#main">Ke konten utama</a>
    {menuOpen && <button className="mobile-scrim" aria-label="Tutup navigasi" onClick={() => setMenuOpen(false)}/>}
    <aside className={`sidebar ${menuOpen ? "open" : ""}`}><Link href="/" className="brand"><span className="brand-mark">e</span><span>enemites<small>ANALYTICS</small></span></Link>
      <div className="workspace-switch"><span className="workspace-avatar">E</span><span>Enemites workspace<small>Landing page</small></span><CaretDownIcon size={13}/></div>
      <div className="nav-label">WORKSPACE</div><nav aria-label="Navigasi utama">{navigation.map(item => <Link key={item.id} href={viewHref(item.id)} onClick={() => setMenuOpen(false)} className={`nav-link ${view === item.id ? "active" : ""}`} aria-current={view === item.id ? "page" : undefined}><item.icon size={19}/>{item.label}{item.id === "waitlist" && data && <span className="nav-count">{data.all.total}</span>}</Link>)}</nav>
      <div className="nav-label system-label">SISTEM</div><Link className={`nav-link ${view === "sources" ? "active" : ""}`} href={viewHref("sources")} onClick={() => setMenuOpen(false)}><DatabaseIcon size={19}/>Sumber data</Link>
      <div className="sidebar-bottom"><div className="connection"><span className={`status-dot ${data ? "" : "offline"}`}/><span>{data ? "Database terhubung" : "Koneksi bermasalah"}<small>Neon · Production</small></span></div><div className="team-account"><div className="team-avatar">EN</div><span>Enemites team<small>Internal access</small></span><form action={logout}><button aria-label="Keluar" title="Keluar"><SignOutIcon size={19}/></button></form></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><button className="menu-toggle" aria-label="Buka navigasi" onClick={() => setMenuOpen(true)}><ListIcon size={22}/></button><div className="breadcrumb">Workspace<span>/</span><b>{view === "sources" ? "Sumber data" : navigation.find(x => x.id === view)?.label}</b></div><div className="topbar-right"><span className="internal-badge"><ShieldCheckIcon size={14}/>Internal only</span><a href="https://enemites.com" target="_blank" rel="noreferrer">Landing page<ArrowUpRightIcon size={15}/></a></div></header>
      <main id="main" className={`main-content ${pending ? "is-pending" : ""}`} aria-busy={pending}>
        <div className="page-heading"><div><div className="eyebrow">LANDING PAGE ANALYTICS</div><h1>{titles[view].title}</h1><p>{titles[view].subtitle}</p></div><div className="heading-controls"><button className={`icon-button ${pending ? "spin" : ""}`} aria-label="Segarkan data" title="Segarkan data" onClick={() => startTransition(() => router.refresh())}><ArrowsClockwiseIcon size={18}/></button>{view !== "sources" && <label className="period-select"><ClockIcon size={16}/><select aria-label="Periode" value={filters.range} onChange={e => update("range", e.target.value)}><option value="all">Semua waktu</option><option value="7">7 hari terakhir</option><option value="30">30 hari terakhir</option><option value="90">90 hari terakhir</option></select><CaretDownIcon size={12}/></label>}</div></div>
        {!data ? <section className="panel error-panel"><WarningCircleIcon size={30}/><h2>Data belum dapat dimuat</h2><p>Periksa koneksi Neon dan izin role dashboard_reader. Data akan muncul setelah koneksi pulih.</p><button className="button" onClick={() => startTransition(() => router.refresh())}>Coba lagi</button></section> : <>
          <div className="data-line"><span><span className="status-dot"/>Data langsung dari Neon</span><span>Disinkronkan {new Date(data.updatedAt).toLocaleTimeString("id-ID", { timeZone: "Asia/Jakarta", hour: "2-digit", minute: "2-digit" })} WIB</span><span className="data-line-last">Pendaftaran terakhir: {date(data.all.last)}</span></div>
          {view !== "forms" && view !== "sources" && <div className="filter-row"><FunnelSimpleIcon size={16}/><span>Filter audiens</span><select aria-label="Perangkat" value={filters.device} onChange={e => update("device", e.target.value)}><option value="">Semua perangkat</option><option>Desktop</option><option>Mobile</option><option>Tablet</option><option value="unknown">Tidak diketahui</option></select><select aria-label="Kelompok umur" value={filters.age} onChange={e => update("age", e.target.value)}><option value="">Semua umur</option>{["<10", "10-18", "18-20", "20+"].map(age => <option key={age}>{age}</option>)}<option value="unknown">Tidak diketahui</option></select><select aria-label="Persetujuan update" value={filters.updates} onChange={e => update("updates", e.target.value)}><option value="">Semua preferensi</option><option value="yes">Menerima update</option><option value="no">Tidak menerima</option></select>{activeFilters && <button className="reset-filter" onClick={() => { const p = new URLSearchParams(searchParams.toString()); ["device", "age", "updates", "page"].forEach(k => p.delete(k)); startTransition(() => router.push("/?" + p.toString(), { scroll: false })); }}>Reset<XIcon size={12}/></button>}</div>}
          {view === "overview" && <>
            <div className="stats-grid"><Metric label="Pendaftar waitlist" value={number(data.stats.total)} icon={<UsersIcon/>} note={filters.range === "all" ? "Seluruh periode terpilih" : data.previous === 0 ? "Periode sebelumnya: 0 pendaftar" : `${Math.round((data.stats.total - (data.previous ?? 0)) / (data.previous || 1) * 100)}% vs periode sebelumnya`} accent/>
              <Metric label="Menerima update" value={number(data.stats.opted_in)} icon={<EnvelopeSimpleIcon/>} note={`${data.stats.total ? Math.round(data.stats.opted_in / data.stats.total * 100) : 0}% menyetujui update`}/>
              <Metric label="Negara teridentifikasi" value={number(data.stats.countries)} icon={<GlobeHemisphereWestIcon/>} note={`${data.stats.unknown_country} pendaftar tanpa lokasi pasti`}/>
              <Metric label="Konversi landing page" value="—" icon={<ChartLineUpIcon/>} note="Data kunjungan belum tersedia" muted/>
            </div><div className="overview-charts"><SignupChart points={data.chart} total={data.stats.total}/><Segments title="Perangkat audiens" description="Perangkat saat bergabung" segments={data.groups.device_type} total={data.stats.total} donut/></div>
            <div className="insight-strip"><div className="insight-icon"><DatabaseIcon size={19}/></div><div><b>Angka yang berasal dari data.</b><p>Analytics mencakup pendaftaran waitlist. Trafik, sumber kunjungan, dan konversi belum tercatat di database.</p></div><Link href={viewHref("sources")}>Lihat sumber<ArrowUpRightIcon size={15}/></Link></div>
          </>}
          {(view === "overview" || view === "waitlist") && <section className="panel table-panel"><div className="panel-head table-heading"><div><h2>{view === "overview" ? "Pendaftaran terbaru" : "Daftar waitlist"}<span className="count-pill">{number(data.matches)}</span></h2><p>{filters.search ? `Hasil pencarian untuk “${filters.search}”` : "Pendaftar pada periode dan filter terpilih"}</p></div><div className="table-actions"><form className="search-field" onSubmit={e => { e.preventDefault(); update("search", search); }}><MagnifyingGlassIcon size={16}/><input aria-label="Cari pendaftar" placeholder="Cari nama, email, telepon…" value={search} onChange={e => setSearch(e.target.value)}/>{search && <button type="button" aria-label="Hapus pencarian" onClick={() => { setSearch(""); update("search", ""); }}><XIcon size={13}/></button>}</form><button className="button export-button" disabled={exporting || data.matches === 0} onClick={exportCsv}><DownloadSimpleIcon size={16}/>{exporting ? "Mengekspor…" : "Ekspor CSV"}</button></div></div>
            {exportError && <p role="alert" className="export-error">{exportError}</p>}
            <div className="table-scroll"><table><thead><tr><th>Pendaftar</th><th>Negara</th><th>Perangkat</th><th>Umur</th><th>Update</th><th>Bergabung</th><th><span className="sr-only">Detail</span></th></tr></thead><tbody>{data.signups.map(row => <tr key={row.id}><td><button className="person-cell" onClick={() => setSelected(row)}><span className="person-avatar">{row.name.trim().slice(0, 2).toUpperCase()}</span><span><b>{row.name}</b><small>{row.email}</small></span></button></td><td>{row.country?.startsWith("Local (") ? "Tidak diketahui" : row.country || "Tidak diketahui"}{row.city && <small className="cell-secondary">{row.city}</small>}</td><td><span className="device-cell"><MonitorIcon size={14}/>{row.device_type || "Tidak diketahui"}</span></td><td>{row.age_group || "—"}</td><td><span className={`consent ${row.receive_updates ? "yes" : ""}`}>{row.receive_updates === null ? "Tidak diketahui" : row.receive_updates ? <><CheckIcon size={12}/>Ya</> : "Tidak"}</span></td><td className="date-cell">{date(row.created_at)}</td><td><button className="row-arrow" aria-label={`Detail ${row.name}`} onClick={() => setSelected(row)}><ArrowUpRightIcon size={17}/></button></td></tr>)}</tbody></table></div>
            {data.signups.length === 0 && <div className="empty-state"><UsersIcon size={30}/><h3>{filters.search ? "Tidak ada hasil yang cocok" : "Belum ada pendaftar"}</h3><p>{filters.search ? "Coba nama atau email lain, atau hapus pencarian." : "Pendaftaran baru akan muncul di sini. Coba periode Semua waktu untuk melihat riwayat."}</p></div>}
            <div className="table-footer"><span>{data.matches ? `${(data.page - 1) * 10 + 1}–${Math.min(data.page * 10, data.matches)} dari ${number(data.matches)} pendaftar` : "0 pendaftar"}</span><div><button disabled={data.page <= 1 || pending} aria-label="Halaman sebelumnya" onClick={() => update("page", String(data.page - 1))}><CaretLeftIcon size={14}/></button><span>Halaman {data.page} dari {data.pages}</span><button disabled={data.page >= data.pages || pending} aria-label="Halaman berikutnya" onClick={() => update("page", String(data.page + 1))}><CaretRightIcon size={14}/></button></div></div>
          </section>}
          {view === "audience" && <><div className="audience-intro"><span className="big-number">{number(data.stats.total)}</span><span>pendaftar dalam segmen terpilih<br/><small>Data lokasi yang kosong atau berupa timezone dikelompokkan sebagai tidak diketahui.</small></span></div><div className="audience-grid"><Segments title="Negara" segments={data.groups.country} total={data.stats.total}/><Segments title="Kelompok umur" segments={data.groups.age_group} total={data.stats.total}/><Segments title="Perangkat" segments={data.groups.device_type} total={data.stats.total} donut/><Segments title="Browser" segments={data.groups.browser} total={data.stats.total}/><Segments title="Sistem operasi" segments={data.groups.operating_system} total={data.stats.total}/><Segments title="Preferensi update" segments={[{ label: "Menerima update", count: data.stats.opted_in }, { label: "Tidak / belum menyetujui", count: data.stats.total - data.stats.opted_in }]} total={data.stats.total} donut/></div></>}
          {view === "forms" && <><div className="stats-grid forms-stats"><Metric label="Total formulir" value={String(data.forms.length)} icon={<ClipboardTextIcon/>} note="Seluruh formulir di database"/><Metric label="Formulir aktif" value={String(data.forms.filter(f => f.is_active && (!f.expires_at || new Date(f.expires_at) > new Date(data.updatedAt))).length)} icon={<CheckIcon/>} note="Aktif dan belum kedaluwarsa"/><Metric label="Respons pada periode" value={String(data.forms.reduce((n, f) => n + f.count, 0))} icon={<EnvelopeSimpleIcon/>} note="Mengikuti filter periode"/></div><section className="panel"><div className="panel-head"><div><h2>Formulir landing page</h2><p>Data formulir dan respons dari database bersama</p></div></div>{data.forms.length ? <div className="forms-list">{data.forms.map(f => <article key={f.id}><ClipboardTextIcon size={24}/><div><h3>{f.title}</h3><p>{f.slug}</p></div><span className="consent">{f.is_active && (!f.expires_at || new Date(f.expires_at) > new Date(data.updatedAt)) ? "Aktif" : "Nonaktif / kedaluwarsa"}</span><b>{f.count} respons periode ini<small className="cell-secondary">{f.total_count} sepanjang waktu</small></b></article>)}</div> : <div className="empty-state forms-empty"><div className="empty-icon"><ClipboardTextIcon size={30}/></div><h3>Belum ada formulir</h3><p>Formulir yang dibuat di landing page akan tampil di sini beserta jumlah responsnya.</p><a className="button" href="https://enemites.com" target="_blank" rel="noreferrer">Buka landing page<ArrowUpRightIcon size={15}/></a></div>}</section><p className="panel-note">Filter audiens berlaku untuk waitlist. Respons formulir mengikuti periode terpilih saja.</p></>}
          {view === "sources" && <><section className="panel source-card"><div className="panel-head"><div><h2>Koneksi database</h2><p>Sumber yang sama dengan website waitlist</p></div><span className="connected-pill"><span className="status-dot"/>Terhubung</span></div><dl><div><dt>Provider</dt><dd>Neon Postgres</dd></div><div><dt>Project</dt><dd className="mono">floral-flower-85390584</dd></div><div><dt>Database / branch</dt><dd>neondb / production</dd></div><div><dt>Akses dashboard</dt><dd>Read-only · dashboard_reader</dd></div><div><dt>Zona waktu laporan</dt><dd>Asia/Jakarta (WIB)</dd></div><div><dt>Pendaftaran terakhir</dt><dd>{date(data.all.last, true)}</dd></div><div><dt>Frontend</dt><dd>Next.js · Vercel / enemites-analytics</dd></div></dl></section><section className="panel source-card"><div className="panel-head"><div><h2>Cakupan analytics</h2><p>Metrik yang tersedia dari sumber saat ini</p></div></div><div className="coverage-list">{[["Waitlist dan persetujuan update", "Tersedia", true], ["Umur, negara, perangkat, browser", "Tersedia jika tercatat", true], ["Formulir dan jumlah respons", "Tersedia", true], ["Pengunjung, pageview, sumber trafik", "Belum tercatat", false], ["Rasio konversi kunjungan ke waitlist", "Memerlukan data kunjungan", false]].map(([label, status, yes]) => <div key={String(label)}><span>{label}</span><span className={yes ? "coverage-yes" : "coverage-no"}>{status}</span></div>)}</div><div className="source-footnote">Dashboard membaca tabel <code>waitlist</code>, <code>enemites_forms</code>, dan <code>enemites_form_submissions</code>. Tidak ada data contoh atau angka estimasi.</div></section></>}
          <footer className="page-footer"><span>Enemites analytics<span className="footer-dot">·</span>Internal workspace</span><span><ShieldCheckIcon size={13}/>Akses baca saja<span className="footer-dot">·</span>WIB (UTC+7)</span></footer>
        </>}
      </main>
    </div>
    <dialog ref={dialogRef} className="detail-dialog" onCancel={() => setSelected(null)} onClick={e => { if (e.target === e.currentTarget) setSelected(null); }}>{selected && <div className="detail-content"><div className="detail-head"><span className="eyebrow">DETAIL PENDAFTAR</span><button className="icon-button" aria-label="Tutup detail" onClick={() => setSelected(null)}><XIcon size={19}/></button></div><span className="detail-avatar">{selected.name.slice(0, 2).toUpperCase()}</span><h2>{selected.name}</h2><p>{selected.email}</p><dl>{[["Telepon / WhatsApp", selected.phone_number], ["Kelompok umur", selected.age_group], ["Persetujuan update", selected.receive_updates === null ? "Tidak diketahui" : selected.receive_updates ? "Ya" : "Tidak"], ["Negara", selected.country], ["Kota", selected.city], ["Perangkat", selected.device_type], ["Browser", selected.browser], ["Sistem operasi", selected.operating_system], ["Bergabung (WIB)", date(selected.created_at, true)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "Tidak diketahui"}</dd></div>)}</dl><p className="detail-note"><ShieldCheckIcon size={14}/>Data internal · hanya untuk tim Enemites</p></div>}</dialog>
  </div>;
}
function Metric({ label, value, note, icon, accent = false, muted = false }: { label: string; value: string; note: string; icon: React.ReactNode; accent?: boolean; muted?: boolean }) {
  return <section className={`metric ${accent ? "accent" : ""} ${muted ? "muted-metric" : ""}`}><div className="metric-label"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><div className="metric-note">{note}</div></section>;
}
